### ISSUE TITLE
MSVC, assert, one more case

### ISSUE THREAD

**Issue by Feacur** [Phyronnaz/UECompilationTimesVisualizer#2]
Hi, thank you for the tool. Just checked out it on the following project. (As a matter of fact, compiler and linker options are currently commented in "premake.lua")

[repository](https://github.com/Feacur/customenginestudy), in case one wonders
and one of the logs [demo_game.log](https://github.com/Phyronnaz/UECompileTimesVisualizer/files/2784454/demo_game.log)

Excerpt from the "main.py" output:
```
Traceback (most recent call last):
  File "main.py", line 276, in <module>
    assert False, "Invalid file name: " + line
AssertionError: Invalid file name:
```

However I figured to replace "assert False ..." line with mere "continue" and successfuly got all respective "*.csv" files. So, no sweat =)

**Comment by Phyronnaz** [comment]
You have additional sections (`Project/Target/Task Performance Summary:`) which is probably why the parser is crashing.
As this seemed to be caused by a custom config, I don't think the script should try to support those.

> However I figured to replace "assert False ..." line with mere "continue" and successfuly got all respective "*.csv" files. 

If you managed to make it work, I'd say the issue is fixed ;)
