### ISSUE TITLE
UE4.20 and 4.21 default toolchain version doesn't support /d1reportTime

### ISSUE THREAD

**Issue by james-terry** [Phyronnaz/UECompilationTimesVisualizer#3]
In UEBuildWindows.cs, the DefaultVisualStudioToolchainVersion is set to 14.13.26128 which is under the required version in VCToolChain.cs of 14.14.26316

It would be useful to update the UE4 setup instructions to make sure that the toolchain default is set to >= 14.14.26316 or that the default toolchain is uninstalled prior to building, otherwise you get an output that skips the Include/Function sections and breaks the python parser.

**Comment by Phyronnaz** [comment]
Thanks, I've updated the readme and the BuildConfiguration to use the latest toolchain available.
